<a href="https://colab.research.google.com/github/MurtazaMister/ML/blob/master/ML_Lab04.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [25]:
import numpy as np
import torch
import torch.nn as nn

In [26]:
inputs = np.array([[73, 67, 43], [91, 88, 64], [87, 134, 58],
                   [102, 43, 37],[69, 96, 70], [73, 67, 43],
                   [91, 88, 64], [87, 134, 58], [102, 43, 37], 
                   [69,96, 70], [73, 67, 43], [91, 88, 64]], dtype='float32')

targets = np.array([[56, 70], [81, 101], [119, 133], [22, 37], 
                    [103, 119],[56, 70], [81, 101], [119, 133], 
                    [22, 37], [103, 119],[56, 70], [81, 101]],dtype='float32')

inputs, targets

(array([[ 73.,  67.,  43.],
        [ 91.,  88.,  64.],
        [ 87., 134.,  58.],
        [102.,  43.,  37.],
        [ 69.,  96.,  70.],
        [ 73.,  67.,  43.],
        [ 91.,  88.,  64.],
        [ 87., 134.,  58.],
        [102.,  43.,  37.],
        [ 69.,  96.,  70.],
        [ 73.,  67.,  43.],
        [ 91.,  88.,  64.]], dtype=float32), array([[ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.],
        [ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.],
        [ 56.,  70.],
        [ 81., 101.]], dtype=float32))

In [27]:
inputs = torch.from_numpy(inputs)
targets = torch.from_numpy(targets)

inputs, targets

(tensor([[ 73.,  67.,  43.],
         [ 91.,  88.,  64.],
         [ 87., 134.,  58.],
         [102.,  43.,  37.],
         [ 69.,  96.,  70.],
         [ 73.,  67.,  43.],
         [ 91.,  88.,  64.],
         [ 87., 134.,  58.],
         [102.,  43.,  37.],
         [ 69.,  96.,  70.],
         [ 73.,  67.,  43.],
         [ 91.,  88.,  64.]]), tensor([[ 56.,  70.],
         [ 81., 101.],
         [119., 133.],
         [ 22.,  37.],
         [103., 119.],
         [ 56.,  70.],
         [ 81., 101.],
         [119., 133.],
         [ 22.,  37.],
         [103., 119.],
         [ 56.,  70.],
         [ 81., 101.]]))

In [28]:
# Import tensor dataset and data loader
from torch.utils.data import TensorDataset, DataLoader
import torch.nn.functional as F

In [29]:
# Define dataset
dataset = TensorDataset(inputs,targets)
dataset[0]

(tensor([73., 67., 43.]), tensor([56., 70.]))

In [30]:
# Define data loader
dataloader = DataLoader(dataset,batch_size=15, shuffle=True)

In [31]:
# Define a model using nn.Linear
# Initializing weights and biases - nn.Linear

model = nn.Linear(in_features=3, out_features=2, bias=True)

In [32]:
# Manipulating the weights and biases - optimizer - optim.SGD
optimizer = torch.optim.SGD(model.parameters(), 0.0001)

In [33]:
# Loss function - torch.nn.functional.mse_loss
loss_fn = F.mse_loss

In [34]:
def fit(num_epochs:int, model, loss_fn, optimizer):
  for epoch in range(num_epochs):
    batch = 0
    for xb,yb in dataloader:
      batch += 1
      pred = model(xb)
      loss = loss_fn(pred, yb)
      optimizer.zero_grad()
      loss.backward()
      optimizer.step()
      print('epoch {} batch {} batch size {} loss {}'.format(epoch,batch,len(xb),loss.item()))

fit(1000, model, loss_fn, optimizer)

epoch 0 batch 1 batch size 12 loss 11664.5947265625
epoch 1 batch 1 batch size 12 loss 6838.74462890625
epoch 2 batch 1 batch size 12 loss 4061.846923828125
epoch 3 batch 1 batch size 12 loss 2458.648681640625
epoch 4 batch 1 batch size 12 loss 1528.3271484375
epoch 5 batch 1 batch size 12 loss 984.2592163085938
epoch 6 batch 1 batch size 12 loss 662.3553466796875
epoch 7 batch 1 batch size 12 loss 468.6302795410156
epoch 8 batch 1 batch size 12 loss 349.2098693847656
epoch 9 batch 1 batch size 12 loss 273.1764831542969
epoch 10 batch 1 batch size 12 loss 222.75294494628906
epoch 11 batch 1 batch size 12 loss 187.68890380859375
epoch 12 batch 1 batch size 12 loss 162.0469970703125
epoch 13 batch 1 batch size 12 loss 142.3654022216797
epoch 14 batch 1 batch size 12 loss 126.60446166992188
epoch 15 batch 1 batch size 12 loss 113.54456329345703
epoch 16 batch 1 batch size 12 loss 102.44052124023438
epoch 17 batch 1 batch size 12 loss 92.82331085205078
epoch 18 batch 1 batch size 12 loss 8

In [35]:
new_data = torch.Tensor([[87, 134, 58], [102, 43, 37], [69, 96,70]])
new_targets = torch.Tensor([[119, 133], [22, 37], [103, 119]])
pred_new_data = model(new_data)
print("Predict (after training): ",new_targets,"\n", pred_new_data)

Predict (after training):  tensor([[119., 133.],
        [ 22.,  37.],
        [103., 119.]]) 
 tensor([[118.5950, 132.9532],
        [ 20.8488,  37.0203],
        [101.6978, 119.1641]], grad_fn=<AddmmBackward0>)
